apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp
  labels:
    app: djangoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      containers:
      - image: us.icr.io/sn-labs-lavanyas/djangoapp:v1
        imagePullPolicy: Always
        name: djangoapp
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
